name: Unit tests

on:
  push:
    branches: [ "master" ]
    paths:
      - 'examples/**'
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Build tests
      # Build / Execute tests defined in tests folder
      working-directory: ${{ github.workspace }}/tests
      run: make

    - name: Execute tests
      # Build / Execute tests defined in tests folder
      working-directory: ${{ github.workspace }}/tests
      #run: make test
      run: bin/connect_spec && bin/publish_spec && bin/receive_spec && bin/subscribe_spec

#    - name: Build on Arduino CLI
#      run: bash .github/build-arduino.sh
